### PR TITLE
Adding Sphinx documentation

### PR DESCRIPTION
**Pull request by wathen**
Adding basic sphinx documentation which separates bits of the readme into different pages

Note:
When building the docs on your local machine I would recommend creating a new python environment via conda.

Checks:

1. Make sure install scripts in `github-actions` folder run locally (suggest to do this in a conda environment)
2. Docs build locally (`cd docs && python -m pip install -r requirements.txt && make html`)
3. Check documentation is adequate 

once PR is merged then I will link it to read the docs

### CODE REVIEW

**Comment by jimc101** [comment]
I am getting an m2r2 error when running `make html`:

```
~/code/git/ersem-github/ersem/docs$ make html
Running Sphinx v1.7.6

Extension error:
Could not import extension m2r2 (exception: No module named 'm2r2')
make: *** [Makefile:20: html] Error 2
```

This is in a clean conda environment (python 3.8), and after running:

```
(ersem-docs) $ python -m pip install -r requirements.txt
```

I can import m2r2 after striking up the python interpreter. Did you see this in your testing? I guess I am missing something simple.

**Comment by wathen** [comment]
> m2r2

We have to use the `m2r2` module so that sphinx can render the readme (that is in markdown) into rst for the docs. 

Does `make install` not work after running `python -m pip install -r requirements.txt`?

**Comment by jimc101** [comment]
I see the installation scripts invoke sudo. Is this necessary? Can that library be installed in a conda env if one is first set up? Or perhaps a check put in place to see if it is already installed, and to skip the sudo step if it is found?

**Comment by wathen** [comment]
I suppose one could install everything into a conda environment though this will add

**Comment by jimc101** [comment]
It's definitely more succinct without setting up a conda env. However, if new libraries need to be installed to have this work locally, I think it will need extending. For example, the scripts invoke the debian package manager which won't work on my local machine running Fedora. Furthermore, libraries may have different names on different systems. I think the use of sudo is also an issue since not all users who want to run the script will have root privileges.

When I first picked this up, I wasn't sure that I had to run the build to generate the documentation? But this is the case?

**Comment by wathen** [comment]
You don't need to run the build scripts locally for the documentation. I just use an `include` or similar to add the scripts to the docs. To build the docs all you need to do is to check out the correct branch and then run `cd docs && python -m pip install -r requirements.txt && make html`

**Comment by jimc101** [comment]
Okay, the docs now build. The problem was that I had created a clean conda environment in which to build to build the docs. I installed the dependencies in the requirements file, but it looks like this only includes a couple of extra dependencies that people might not have installed already. For example, it doesn't include sphinx itself. Adding sphinx and and sphinx_rtd_theme allows it to build. Could these be added to the requirements file?

The docs themselves are a good start. I did get the warning:

...index.rst:: WARNING: image file not readable: ../../images/ERSEM.png

although an image was still incorporated into the docs. The docs need some editing and I am wary about adding partially complete docs to readthedocs. I would prefer to get the docs to a place where we are relatively happy with them (in a basic sense) before publishing them. Is the need to merge into master now to test that the links to readthedocs can be made?

**Comment by wathen** [comment]
I agree, we should get the docs into a stable state before we merge back into master, I was getting the `WARNING` too but as you said, the image is still incorporated into the docs. I will see if I can find why.

I'll add `sphinx` and `sphinx_rtd_theme` to the requirements file.

**Comment by r4ecology** [comment]
Looking through this now. I like the look of it.

Is there a way to get the search fully functional? It seems to only look for page headers, at least when try.

**Comment by wathen** [comment]
> Looking through this now. I like the look of it.
> 
> Is there a way to get the search fully functional? It seems to only look for page headers, at least when try.

I will have a look to see

**Comment by r4ecology** [comment]
> > Looking through this now. I like the look of it.
> > Is there a way to get the search fully functional? It seems to only look for page headers, at least when try.
> 
> I will have a look to see

I thought this was done automatically by readthedocs actually. Probably wrong. I can have a look at the docs for nctoolkit and see if there is something in there to make searching smoother. Most likely just one line of code

**Comment by hpowley** [comment]
This looks really good Michael and Jim.  I'm not sure the level of detail you want at the moment but one comment on building GOTM is that if I use the scripts in the tutorial I get the following error (due to grfortran version) when running make install: 

Error: Assignment to contiguous pointer from non-contiguous target at (1)

To get round this I have to add the following to my cmake command -DFABM_USE_CONTIGUOUS=OFF.  It may be worth adding this to the tips and troubleshooting part?

**Comment by wathen** [comment]
> This looks really good Michael and Jim. I'm not sure the level of detail you want at the moment but one comment on building GOTM is that if I use the scripts in the tutorial I get the following error (due to grfortran version) when running make install:
> 
> Error: Assignment to contiguous pointer from non-contiguous target at (1)
> 
> To get round this I have to add the following to my cmake command -DFABM_USE_CONTIGUOUS=OFF. It may be worth adding this to the tips and troubleshooting part?

Do you know what version of `gfortran` you are using? Would be good to add that to the tutorial as well as the `-DFABM_USE_CONTIGUOUS=OFF` to the tips section

**Comment by hpowley** [comment]
> > This looks really good Michael and Jim. I'm not sure the level of detail you want at the moment but one comment on building GOTM is that if I use the scripts in the tutorial I get the following error (due to grfortran version) when running make install:
> > Error: Assignment to contiguous pointer from non-contiguous target at (1)
> > To get round this I have to add the following to my cmake command -DFABM_USE_CONTIGUOUS=OFF. It may be worth adding this to the tips and troubleshooting part?
> 
> Do you know what version of `gfortran` you are using? Would be good to add that to the tutorial as well as the `-DFABM_USE_CONTIGUOUS=OFF` to the tips section

I'm using Compiler: GNU 8.3.1.  I think the issue may be for version 8.x

**Comment by r4ecology** [comment]
> > > This looks really good Michael and Jim. I'm not sure the level of detail you want at the moment but one comment on building GOTM is that if I use the scripts in the tutorial I get the following error (due to grfortran version) when running make install:
> > > Error: Assignment to contiguous pointer from non-contiguous target at (1)
> > > To get round this I have to add the following to my cmake command -DFABM_USE_CONTIGUOUS=OFF. It may be worth adding this to the tips and troubleshooting part?
> > 
> > 
> > Do you know what version of `gfortran` you are using? Would be good to add that to the tutorial as well as the `-DFABM_USE_CONTIGUOUS=OFF` to the tips section
> 
> I'm using Compiler: GNU 8.3.1. I think the issue may be for version 8.x

This raises a question. Can you create a conda environment to run the tutorials? That is potentially a way round some of these issues.

**Comment by wathen** [comment]
> > > > This looks really good Michael and Jim. I'm not sure the level of detail you want at the moment but one comment on building GOTM is that if I use the scripts in the tutorial I get the following error (due to grfortran version) when running make install:
> > > > Error: Assignment to contiguous pointer from non-contiguous target at (1)
> > > > To get round this I have to add the following to my cmake command -DFABM_USE_CONTIGUOUS=OFF. It may be worth adding this to the tips and troubleshooting part?
> > > 
> > > 
> > > Do you know what version of `gfortran` you are using? Would be good to add that to the tutorial as well as the `-DFABM_USE_CONTIGUOUS=OFF` to the tips section
> > 
> > 
> > I'm using Compiler: GNU 8.3.1. I think the issue may be for version 8.x
> 
> This raises a question. Can you create a conda environment to run the tutorials? That is potentially a way round some of these issues.

Do you mean a conda build for ERSEM or to run the tutorials within in a conda enviroment which you use to install the required packages?

**Comment by r4ecology** [comment]
> > > > > This looks really good Michael and Jim. I'm not sure the level of detail you want at the moment but one comment on building GOTM is that if I use the scripts in the tutorial I get the following error (due to grfortran version) when running make install:
> > > > > Error: Assignment to contiguous pointer from non-contiguous target at (1)
> > > > > To get round this I have to add the following to my cmake command -DFABM_USE_CONTIGUOUS=OFF. It may be worth adding this to the tips and troubleshooting part?
> > > > 
> > > > 
> > > > Do you know what version of `gfortran` you are using? Would be good to add that to the tutorial as well as the `-DFABM_USE_CONTIGUOUS=OFF` to the tips section
> > > 
> > > 
> > > I'm using Compiler: GNU 8.3.1. I think the issue may be for version 8.x
> > 
> > 
> > This raises a question. Can you create a conda environment to run the tutorials? That is potentially a way round some of these issues.
> 
> Do you mean a conda build for ERSEM or to run the tutorials within in a conda enviroment which you use to install the required packages?

I was thinking of creating a conda environment for running the tutorials. Potentially that would make life easier for some, and you would get around any version issues, such as the gfortran one. I suspect wrapping it up as conda package might be too time consuming. Though it would make things more reproducible

**Comment by wathen** [comment]
> > > > > > This looks really good Michael and Jim. I'm not sure the level of detail you want at the moment but one comment on building GOTM is that if I use the scripts in the tutorial I get the following error (due to grfortran version) when running make install:
> > > > > > Error: Assignment to contiguous pointer from non-contiguous target at (1)
> > > > > > To get round this I have to add the following to my cmake command -DFABM_USE_CONTIGUOUS=OFF. It may be worth adding this to the tips and troubleshooting part?
> > > > > 
> > > > > 
> > > > > Do you know what version of `gfortran` you are using? Would be good to add that to the tutorial as well as the `-DFABM_USE_CONTIGUOUS=OFF` to the tips section
> > > > 
> > > > 
> > > > I'm using Compiler: GNU 8.3.1. I think the issue may be for version 8.x
> > > 
> > > 
> > > This raises a question. Can you create a conda environment to run the tutorials? That is potentially a way round some of these issues.
> > 
> > 
> > Do you mean a conda build for ERSEM or to run the tutorials within in a conda enviroment which you use to install the required packages?
> 
> I was thinking of creating a conda environment for running the tutorials. Potentially that would make life easier for some, and you would get around any version issues, such as the gfortran one. I suspect wrapping it up as conda package might be too time consuming. Though it would make things more reproducible

Happy to put the tests into a conda enviroment on github actions though this should be done in a different issue?

**Pull request merged**
