### PR TITLE
Remove unused params in oxygen module for iswO2

### LINKED ISSUE #51: The description of the oxygen parameter iswO2 is incorrect
The iswO2 parameter controls the method used to compute oxygen saturation concentrations. The description of the parameter incorrectly suggests options for "Nightingale et al 2000" and "Wanninkhof 2014" can be specified. This is not the case - only the "legacy ERSEM" and "Weiss 1970" options have been implemented.

### PR DESCRIPTION
**Pull request by wathen**
#### Description of Work

Fixes #51 

#### Testing Instructions

1. Check right optional parameters have been removed

### CODE REVIEW

**Comment by wathen** [comment]
@jimc101 from the description in the issue you say that "legacy ERSEM" and "Weiss 1970"  are the only options to choice from though it looks like the options are "legacy ERSEM" and "Wanninkhof 2014" from the code 

https://github.com/pmlmodelling/ersem/blob/7acae16dfc4ec8b1aab4376bdbf28c241f9be2e4/src/oxygen.F90#L101-L109

**Review by jimc101 — CHANGES_REQUESTED** [review]
Sorry, this isn't right. The option relates to the code [here](https://github.com/pmlmodelling/ersem/blob/b319eecef5607f218fb6b0f109b5a8ef2de585af/src/oxygen.F90#L164) and the way the saturation concentration is calculated.

This option should be reduced to legacy (or old) ERSEM and Weiss 1970. I would put Weiss first, since this is the option most users are likely to select. Also, there is no guard for invalid values. So something like:

```
if weiss:
    ...
elif old_ersem:
    ...
else
    throw exception
fi
```
could work. These would need to be matched up in the call to `get_parameter`. What do you think?

**Comment by wathen** [comment]
Ahh I see, yes we could have a function called `get_parameter` though if it is only used here then there might be now point really

**Comment by wathen** [comment]
@jimc101 having a safe guide for an incorrect parameter would be good in most places in the code though that would be done in a separate issue

**Comment by jimc101** [comment]
Sorry - I recommend you switch to just deleting the invalid options in the text string and not reordering the loop. This can be addressed in a separate issue (under optimisations). As you say, all valid options should also be tested, but again this can be addressed through a separate issue.

**Review by jimc101 — APPROVED** [review]
Okay - looks good.

**Pull request merged**
